# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/nic/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

packages:
- ../../programming/nick-chandoke/niclib/
- ../../programming/nick-chandoke/lookupt/
- ../../programming/nick-chandoke/nixys-server-box/
- ../../programming/nick-chandoke/data-manip/
resolver: lts-14.3

extra-deps:
- aws-0.21.1@sha256:5290b819bd425f28c736b93a84955ced145bdb631a26d784d1b952e2e0ddc6b8
- bytestring-trie-0.2.5.0@sha256:96498959cf2af0e3f1f3dfb526b78502c9fa8f21255a3506938ee2a26e61d653
- typed-process-0.2.6.0
# - stripe-core-2.4.1
# - stripe-http-client-2.4.1
# - suffixtree-0.2.2.1@sha256:cebcb1310034a6a4d5f9febececb1a8c28fe411376c6fca0faf1b4b0cdf4c176
# - time-1.9.2
- fgl-visualize-0.1.0.1@sha256:e682066053a6e75478a08fd6822dd0143a3b8ea23244bdb01dd389a266447c5e,995
- topograph-1@sha256:315dfa22bfdc94ce67380c989b4ce304477ec982e1d663895607eaabc3159169,1598
