# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The following parameters are used by "stack new" to automatically fill fields
# in the cabal config. We recommend uncommenting them and filling them out if
# you intend to use 'stack new'.
# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
templates:
  params:
     author-name: Nicholas Chandoke
     author-email: nicholas.chandoke@gmail.com
     copyright: 2016-2020 Nicholas Adri Chandoke
     github-username: nick-chandoke

allow-newer: true

# for building xmonad on nix:
# note that zlib is needed for Cabal, too.
nix:
  enable: true
  packages:
#       - libffi
        - zlib.dev
        - zlib.out
#        - cairo
#       - gcc
#        - gnome2.pango
#        - gtk2-x11
#        - libxml2
#        - pkgconfig
#        - upower
#        - x11
#        - xorg.libX11
#        - xorg.libXext
#        - xorg.libXinerama
#        - xorg.libXrandr
#        - xorg.libXrender
#        - xorg.libXScrnSaver
